### ISSUE TITLE
Old-school method for "no Tank config" seems to let the bot stick in-game

### ISSUE THREAD

**Issue by jensewe** [SirPlease/L4D2-Competitive-Rework#107]
- Was Nextmod 1v1. Not sure in what case it could still spawn a tank but the plugin _(**l4d_notank.smx**)_ is definitely to blame.

> Not resized :(

![TIM图片20200925191523](https://user-images.githubusercontent.com/33988868/94261474-85832b80-ff64-11ea-8519-ab673c8b369a.jpg)

**Comment by jensewe** [comment]
Out of topic here, another wrong codes in [l4d2_weapon_attributes](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_weapon_attributes.sp#L270).

**Comment by SirPlease** [comment]
Thanks for reporting to the github, I'll put it on the low priority right now as we've got some serious things to tackle first.
As for your off topic note, it's fixed in the .smx, there's a few plugins in here that I simply forgot to update the sourcefiles for, I'll get to it!

I'll keep this issue open until I've investigated the issue.
