### ISSUE TITLE
readyup.sp

### ISSUE THREAD

**Issue by squishiness** [SirPlease/L4D2-Competitive-Rework#110]
Hi Sir,

Can you commit the readyup.sp file as well please

**Comment by SirPlease** [comment]
I went ahead and investigated an issue that was rather low priority, I'm assuming this is why you requested it 😄 
OnPluginEnd() couldn't properly fire due to readyup's dependencies which would be unloaded before readyup, I'm pushing a new plugin (along with readyup) to the repo that will ensure readyup's leftovers are reset on matchmode unload.
