### ISSUE TITLE
Chargers can stumble tanks in ZoneMod 1.9.9

### ISSUE THREAD

**Issue by ProdigySim** [SirPlease/L4D2-Competitive-Rework#115]
It sounds like maybe they shouldn't be able to.

**Comment by ProdigySim** [comment]
This is the relevant plugin, looks like it's using CBaseEntity data offsets. https://github.com/Attano/L4D2-Competitive-Framework/blob/master/addons/sourcemod/scripting/l4d2_si_staggers.sp

**Comment by jensewe** [comment]
I believe it's because the "source" index of charger impact is changed from 0 to -1, probably due to internal stuff of l4dhooks.

**Comment by devilesk** [comment]
I'm seeing error logs for `l4d2_si_staggers.smx` and I think it's because the configs aren't using the fixed version. The repo has two versions of l4d2_si_staggers in the plugins folder. The one in `plugins/l4d2_si_staggers.smx` looks like it has been compiled with the latest fixed version but it's not being referenced by any configs. The one in `plugins/optional/l4d2_si_staggers.smx` doesn't have the fix but it's the one referenced in configs https://github.com/SirPlease/L4D2-Competitive-Rework/blob/aff0902a98671fe9296c2915cdc13d1bdca6550f/cfg/cfgogl/zonemod/shared_plugins.cfg#L77
