### ISSUE TITLE
L4D2 Antibaiter issues

### ISSUE THREAD

**Issue by SirPlease** [SirPlease/L4D2-Competitive-Rework#134]
Video of [issue](https://www.twitch.tv/videos/754120639?t=1h20m14s)
- Offsets are correct.
- This appears to be an issue that was already present in the plugin but was never addressed, not related to the patch.
- Looks like while it cancels the timer on the hud from showing up, it doesn't care about the internal plugin timer.

**Comment by devilesk** [comment]
> Looks like while it cancels the timer on the hud from showing up, it doesn't care about the internal plugin timer.

I did some testing and the countdown timer on the hud goes away just from the round change and not because the plugin is doing anything to cancel it. So the previous round's countdown timer is still counting down and elapsing, but you don't see it in the hud.

The plugin resets the infected alive time when the round goes live which is only enough to prevent the horde spawn logic from spawning a horde until 20 seconds after the round goes live as seen in the VOD. The rest of the horde spawning conditions are already satisfied, because the timer and the other variables didn't get reset from last round.
