### ISSUE TITLE
L4D2 Weapon Attribute issue

### ISSUE THREAD

**Issue by A1oneR** [SirPlease/L4D2-Competitive-Rework#145]
When the mode is loaded, the weapon attribute seem like this
Damage for pumpshotgun set to 14
Bullets for pumpshotgun set to 20
Range for pumpshotgun set to 4.25
Range modifier for pumpshotgun set to 4.25
Damage for shotgun_chrome set to 16
Bullets for shotgun_chrome set to 16
Range for shotgun_chrome set to 3.25
Range modifier for shotgun_chrome set to 3.25
Bullets for smg set to 0.25
Damage for smg set to 22
Min ducking spread for smg set to 1.85
Bullets for smg_silenced set to 0.31
Min ducking spread for smg_silenced set to 2.15
Penetration max dist for smg_silenced set to 0.79

After completely searching for the probably issue , it seems the attributes needed to change get something wrong like this.

![20201005012443](https://user-images.githubusercontent.com/70164765/95022383-968d1480-06a9-11eb-9738-b1a6748f9672.png)

Sorry For My Poor English.

**Comment by SirPlease** [comment]
It's a visual thing in console as I converted the plugin from the old method to the new method (instead of a combined array, to a split array of `integers` and `floats`.
The weapon values are set properly, but the console print will show the wrong attribute for the `floats`.

The console command is fixed however, you can use `sm_weapon_attributes <weapon>` in console as a player to check the values of a weapon.

I'll leave this issue open as I'll fix this one including being unable to change weapons after changing them once.
