### ISSUE TITLE
[Question / bug ?] sv_consistency_fixes

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#182]
Is it normal that every round start there is a freeze of 5 seconds for everyone on the server ? Sometimes a few players are getting stuck and ask why they can't move even after this massive freeze.

By the way this is not happening if i leave sv_consistency to 0 in the server.cfg, but i'm guessing this plugin alone does not help to check the files of clients then.

Is it enough to have sv_pure 1 with a whitelist + the addonconfig disabling mods in versus, or is it really necessary to have sv_consistency set to 1 to fight cheaters?

By the way if i set up sv_consistency to 1 without your plugin, the freezes happens randomly anytime.

**Comment by SirPlease** [comment]
> Is it normal that every round start there is a freeze of 5 seconds for everyone on the server ? Sometimes a few players are getting stuck and ask why they can't move even after this massive freeze.

The duration of the freeze clients endure is totally dependent on the amount of files (and especially their size in mb) you are forcing clients to CRC Check.
It can also have worse effects on clients with higher ping. (Like being stuck longer)

> By the way if i set up sv_consistency to 1 without your plugin, the freezes happens randomly anytime.

The sole purpose of the plugin is to prevent using Valve's behaviour (which by default is to check clients against the whitelist every 3 minutes. (`cl_consistencycheck_interval` controls the time between checks, which by default is `180.0`)
In vanilla this isn't a problem as the default whitelist just checks the base files rather than additional files such as sounds.

> Is it enough to have sv_pure 1 with a whitelist + the addonconfig disabling mods in versus, or is it really necessary to have sv_consistency set to 1 to fight cheaters?

sv_consistency is a must have, if you simply don't want to have these freezes then just leave the whitelist file as Valve's default + gameinfo.
I do recommend looking into getting a decent enough whitelist file that doesn't cause too big of an annoyance to your players.

**Comment by lunatixxx** [comment]
Will it help if i just leave check_crc and remove check every map ? It will just check one time when the client is connecting the first time i'm guessing.

**Comment by SirPlease** [comment]
The consistency check is called on `OnClientConnected` in the plugin, if you want to only check the client once (on first connect) I suggest moving the code (`ClientCommand(client, "cl_consistencycheck");`) to `Event_PlayerConnectFull` as that only gets called for the first time a client loads in.

**Comment by SirPlease** [comment]
I'll this as I haven't heard back from you in a bit, if you have any more questions feel free to re-open the issue.
