### ISSUE TITLE
Rare case where survivor can move and shoot even impacted by charger

### ISSUE THREAD

**Issue by jensewe** [SirPlease/L4D2-Competitive-Rework#194]
Seems to be charger's M1 on survivor at the very end of playing get-up, where the "capped" survivor will still be free to do anything for a short period, and then get teleported into charger's control.
No video sorry. Blocking buttons of survivors once they should've been capped may be a reasonable way.

**Comment by SirPlease** [comment]
This is an old bug that occurs between the transition from`charger_carry_end` to `charger_pummel_start`.
I remember looking into something related a while ago but dropped it because of all the checks I had to do and felt like it was sloppy, I'll leave this on low priority for now and I'll fix it if I come up with a cleaner solution (and have checked all the related properties to see if they're useful, probably not)
