### ISSUE TITLE
client freezes 

### ISSUE THREAD

**Issue by markgs** [SirPlease/L4D2-Competitive-Rework#201]
Hi,
After loading a matchmode / loading the next map / changing to a different map. The L4D client would freeze for a few seconds then become normal. 
Would this be normal? I thought perhaps sv_consistency_fixes caused the freeze (due to file checking) but I disabled the plugin and still encountered the issue.

**Comment by SirPlease** [comment]
Removing `sv_consistency_fix` simply makes it use Val;ve's default behaviour, which makes checks every 3 minutes.
The issue here is that the files you're checking clients for in the whitelist are either too big, or simply too many.

**Comment by markgs** [comment]
Hi SirPlease,
Yep the issue was with sv_consistency_fixes. I'm using this copy of whitelist.cfg - 
https://github.com/SirPlease/Server4Dead-Project/blob/master/Extensions%2C%20Gamedata%2C%20Competitive%20Preperation/whitelist.cfg

Could you suggest which lines can be deleted? And,would upgrading to an SSD (on the server) speed up checking?

**Comment by SirPlease** [comment]
Upgrading to an SSD doesn't impact the process AFAIK, as it's simple crc checks that are done, the problem lies in that the client needs to verify the file.

That whitelist you're using is a pretty old one, I'm guessing it has lags now because of the The Last Stand update making the update folder quite big.
Try removing the check for `update\*.*+.vpk` just to see if this has any impact.

**Comment by markgs** [comment]
Freeze isn't too noticeable. Will close the case, 
Thank you!
