### ISSUE TITLE
Breakable windows/props behave differently / can't be broken by scratches

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#230]
See the video, first part is on local server, 2nd is on server running this repo.
Also applies to the glass on c1m3, it takes much more damage to break them.

https://youtu.be/rqzh3x_qcFA

**Comment by SirPlease** [comment]
Caused by [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4c920df53fff3370668d7aefb4356b5fd754c18d/addons/sourcemod/scripting/readyup.sp#L1147) in readyup.
Considering removal, as it likely only got added to prevent Survivors shooting physic props in the saferoom.

**Comment by Derpduck** [comment]
While this may "fix" the issue, I don't know if it's the right way to do it still.
A handful of maps do have prop_physics entities with a value other than the default, and custom maps could do anything. The plugin also messes with prop_door_rotating which in the past has caused issues with events tied to doors (c1m3, c12m2). Could props that can be affected during ready up not be addressed on a per-map basis instead of modifying every physics prop.

**Comment by jacob404** [comment]
> 
> 
> Caused by [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4c920df53fff3370668d7aefb4356b5fd754c18d/addons/sourcemod/scripting/readyup.sp#L1147) in readyup.
> Considering removal, as it likely only got added to prevent Survivors shooting physic props in the saferoom.

can confirm it was added for that purpose. originally the plan was to track the state of props and reset them after ready up, along with tracking a bunch of other stuff in an attempt to allow survivors to explore the whole map in ready up without needing a map reload. i was under the impression the state tracking was already implemented before i quit but i guess not. totally safe to remove since it's only relevant in a handful of places and in a trivial way. sorry for the mess i left in my wake by throwing stuff at the wall and seeing what stuck
