### ISSUE TITLE
Direscraper Redux chapter 2: 2nd event spawns no commons

### ISSUE THREAD

**Issue by ProdigySim** [SirPlease/L4D2-Competitive-Rework#233]
If you hold out the first event and kill all commons, the 2nd panic event at the elevator wait will spawn no horde. Seems like a holdout related bug.

**Comment by SirPlease** [comment]
Confirmed.
This is caused by [l4d2_horde_equaliser](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_horde_equaliser.sp) as it doesn't support multiple events on a map (as pointed out to me by [Rena](https://steamcommunity.com/profiles/76561198043042606/)!

**Comment by SirPlease** [comment]
Resolved in Zonemod 1.9.13
