### ISSUE TITLE
Stripper global fixes not loaded on custom campaigns

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#234]
Playing Diescraper and the changes from global_fixes.cfg didn't seem to be loaded/working at all, e.g. physics props are still solid or not filtered out

**Comment by SirPlease** [comment]
Diescraper comes with its own models, this is likely to be the issue.
I'll have to look at other custom campaigns to confirm though.

**Comment by Derpduck** [comment]
They were standard props that are used in all maps, not models included with Diescraper (most of which are very map specific).
I decompiled the map, turns out the map uses `prop_physics_multiplayer` instead of the standard `prop_physics`.
It shouldn't be an issue on other maps unless the map maker uses the "wrong" entity type, should be fixable for just Diescraper.

**Comment by SirPlease** [comment]
Hm, I was under the impression prop_physics_multiplayer were always converted to prop_physics.

**Comment by Derpduck** [comment]
Stripper changes are applied before the map loads, so if a plugin converts the props they still won't be affected by Stripper.
I've committed a fix which fixes issue on Diescraper.

**Comment by MartLegion** [comment]
prop_physics_multiplayer converts into prop_physics after SpawnPost

But since Stripper runs before it, you have to check for the "*multiplayer" name.

There are also other entities with the same behaviour:

- prop_physics
- prop_physics_multiplayer -> prop_physics
- prop_physics_override -> prop_physics
- physics_prop -> prop_physics
