### ISSUE TITLE
code_patcher does not work

### ISSUE THREAD

**Issue by A1mDev** [SirPlease/L4D2-Competitive-Rework#293]
Maybe someone knows how to fix it? What was found:
1) Offset changed CTerrorPlayer::FireBullet_SpreadPatch (new linux offset 1029)
2) Сhanged reverse offset in plugin l4d2_static_shotgun_spread.smx (new g_CenterPelletOffset = -0x1c; old: -0x31)
3) The assembler code is 1 byte shorter in the original function, the assembler code from the plugin is written further by 1 byte (Can break something?)
 
After changing the offset 'CTerrorPlayer::FireBullet_SpreadPatch', it seems to work, but the damage from the shotgun is less, as if it shoots 1 pellet. The plugin 'visualise_impacts.smx' shows exactly this (1 pellet). 

Edit: it seems like here just need to change the registers

**Comment by SirPlease** [comment]
As I said before, to be clear, it does not fire one pellet.
The spread is just really **really** far.

**Comment by robex** [comment]
ASM code changed a bit, now `eax` register is used in the original function instead of `edx` to store whatever is at `arg_18`, and some variable offsets changed as well (`var_ac -> var_65c`, `var_c4 ->var_650`). The reason the spread is wild is because the patch is using the old variable offsets which probably have some unrelated value. I think the register change doesn't influence anything because both `eax` and `edx` are overwritten further down the function anyway, their value is not used anymore.


Here is the pseudocode of the old and new code at `CTerrorPlayer::FireBullet_SpreadPatch`, arrows indicate the changes.

Old:
```
eax = arg_18
*(esp + 8) = xmm0
xmm0 = xmm0 ^ 0x80000000
*esp = "bulletspread"
*(esp + 4) = xmm0
*(esp + 0xc) = eax
call SharedRandomFloat
edx = arg_18		<-----------
pop var_ac		<-----------
*(esp + 8) = 0x43340000
*(esp + 4) = 0
*esp = "spreaddir"
*(esp + 0xc) = edx	<-----------
call SharedRandomFloat
pop var_c4		<-----------
```
New:
```
eax = arg_18
*(esp + 8) = xmm0
xmm0 = xmm0 ^ 0x80000000
*esp = "bulletspread"
*(esp + 4) = xmm0
*(esp + 0xc) = eax
call SharedRandomFloat
eax = arg_18		<-----------
pop var_65c		<-----------
*(esp + 8) = 0x43340000
*(esp + 4) = 0
*esp = "spreaddir"
*(esp + 0xc) = eax	<-----------
call SharedRandomFloat
pop var_650		<-----------
```


The patch has to be modified because the new offsets are 2 bytes instead of 1, which would shift everything if they were in a `mov`. Luckily these offsets are in the `lea` and `fstp` instructions which take a 32-bit value as an operand, so the total number of bytes stays fixed.
```
8d 8d 54 ff ff ff       lea    ecx, [ebp-0xac]    // old
8d 8d a4 f9 ff ff       lea    ecx, [ebp-0x65c]   // new

d9 9d 3c ff ff ff       fstp   DWORD PTR [ebp-0xc4]     // old
d9 9d b0 f9 ff ff       fstp   DWORD PTR [ebp-0x650]    // new
```

I haven't tested if it works because I don't have a l4d2 server environment setup right now, but I will test it later (today, hopefully) and see if it works.
