### ISSUE TITLE
Yama campaign final crash ?

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#322]
I am using the "Yama finale fixed" version on l4dmaps and when going from chapter 4 to final the server crashes while loading without sourcemod error log, if i start from lobby directly the final it loads dead center campaign. It does not happen in solo or local so i guess a plugin  is causing that, do you have this problem too ? I don't have anything special outside of this repository, except sourcetv. It is a scavenge finale so i was wondering if maybe no gas can plugin could be the cause, depending on how it is coded in the vscript of map.

**Comment by SirPlease** [comment]
I'm assuming dead center is your default server map, meaning it crashes while loading the map.
You've been reporting a lot of issues in circumstances that do not occur when using this repository for its original purpose, so you're going to have to provide more information in your bug reports.

Sidenote: The gas can plugin is no longer used in this repo, nor would its original code affect scavenge cans.

**Comment by SirPlease** [comment]
I've gone ahead and tested this on my server which runs an identical install, no issues with loading the map on campaign nor with Zonemod.
I'm afraid this issue is on your end.

I used the map from here: https://www.gamemaps.com/details/22601

Note:
There were 3 new patches to the map after your post, perhaps one of them fixed it.
