### ISSUE TITLE
Stripper model in zonemod c12m1_hilltop uses a model that no longer exists.

### ISSUE THREAD

**Issue by honkthebonk2** [SirPlease/L4D2-Competitive-Rework#34]
On line 103, someone in the past added a fallen tree to let SI get out of the pit at the beginning of the map so that they aren't stuck there forever. However, the model used is one from Cold Stream's early days, and it is now removed from the game.

`"model" "models/gm_forest/deadtrunk.mdl"`

In its place is an error model and SI have no way to get back up in the current version.

On our copy I made a messy fix, but you might be able to get something better.
```add:
; --- prevent SI getting stuck in large ditch near starting area (confogl only)
{
    ; toppled tree ramp in ditch
    "solid" "6"
    "origin" "-8200 -13380 -515"
    "angles" "-67.5 70 0"
    "model" "models/props_foliage/old_tree01.mdl"
    "disableshadows" "1"
    "classname" "prop_dynamic_override"
}
```

**Comment by SirPlease** [comment]
Thanks for the report!

I've decided to stay true to my nature, and use a bus as a prop.
A [beautiful sight](https://steamcommunity.com/sharedfiles/filedetails/?id=1858409243) if I may say so myself. ;)

Fixed in [Update v0.5.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/76309f1d214e06d4e99400ebcc57c714f17f71a3)
