### ISSUE TITLE
Taunt bug

### ISSUE THREAD

**Issue by HunLepto** [SirPlease/L4D2-Competitive-Rework#367]
https://user-images.githubusercontent.com/77020176/131490448-72c54b98-6908-4449-81fb-969b293f1a98.mp4

Tried to keep it as short as possible, basically, the bug is that if you taunt before start-up and keep it on, your character will not be teleported.

**Comment by SirPlease** [comment]
This is a SirPlease Server only issue which was known, but I do appreciate you reporting it.
Issue is caused because I replaced my modified ready-up which kept dances in mind with the updated ready-up without adding the needed forwards.
I'll solve this shortly, I'll close this because it's not related to the repo.
