### ISSUE TITLE
l4d2_weapon_attributes

### ISSUE THREAD

**Issue by oethanx** [SirPlease/L4D2-Competitive-Rework#368]
sm_weapon pistol speed 500
Max player speed for weapon_pistol set to 500.00.

This does not have any effect on movement speed while carrying a pistol, am i modifying it correctly?

**Comment by vikingo12** [comment]
why would your movement speed change? is there even an option for that?

**Comment by oethanx** [comment]
i believe it should be possible to change movement speed while carrying some weapon?

**Comment by vikingo12** [comment]
Even if it has, its never used cause you never get slowdown for carrying m60 or grenadelauncher

**Comment by oethanx** [comment]
That's my point, having a way of making it usable, which is why we have such vast possibilities of modding

Note: CS:GO has this mechanics, this plugin has similar options but it does not have any effect

**Comment by jensewe** [comment]
Survivor speed is somewhat hardcoded in game codes. This attribute can do nothing actually.
There's detour method that allow making changes to survivor speed though. If you're willing to implement this logic on L4D, see if these would be helpful to you (possibly with `l4d2_slowdown_control` as reference):
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/bbfabbca1f0d9cb49ed498a41e7027077241fc6f/addons/sourcemod/scripting/include/left4dhooks.inc#L519
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/bbfabbca1f0d9cb49ed498a41e7027077241fc6f/addons/sourcemod/scripting/include/left4dhooks.inc#L530
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/bbfabbca1f0d9cb49ed498a41e7027077241fc6f/addons/sourcemod/scripting/include/left4dhooks.inc#L541

By the way, there's also a "hidden" one called `ReloadDuration`, probably a better option for `l4d2_smg_reload_tweak`, and any other weapons.

**Comment by SirPlease** [comment]
Not sure whether it's worth modifying the plugin to actually have "speed" work, I feel the only reason this is carried over into the plugin is because of it's position in the game's code.
As pointed out by @jensewe there's a function that does make this possible, and a plugin that possibly already modifies this, which is what makes this outside of the scope of this repository.

I'll close this issue as I do feel your question has been answered, if you disagree, feel free to re-open. :)
