### ISSUE TITLE
autopause 

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#478]
It will pause even for a player that crashed before fully loaded, not appearing in scoreboard. Is it intended?

Maybe if possible ignore players that did not pass  OnClientPostAdminCheck

**Comment by lunatixxx** [comment]
L 05/30/2022 - 22:49:21: [SM] Blaming: autopause.smx
L 05/30/2022 - 22:49:21: [SM] Call stack trace:
L 05/30/2022 - 22:49:21: [SM]   [0] GetClientTeam
L 05/30/2022 - 22:49:21: [SM]   [1] Line 114, plugin.sp::playerDisconnect

Plenty of errors like that.

**Comment by lunatixxx** [comment]
It was the only thing appearing in log. Also was wondering what happens if a vote was in progress and then someone crash and the game pause at this moment, not going to create a bug?

**Comment by SirPlease** [comment]
This would be the full error:

`L 05/31/2022 - 00:06:46: [SM] Exception reported: Client 3 is not in game
L 05/31/2022 - 00:06:46: [SM] Blaming: optional/autopause.smx
L 05/31/2022 - 00:06:46: [SM] Call stack trace:
L 05/31/2022 - 00:06:46: [SM]   [0] GetClientTeam
L 05/31/2022 - 00:06:46: [SM]   [1] Line 117, d:\SourcePawn11\autopause.sp::playerDisconnect`

I'd suggest testing your question by simply just pausing the game yourself during a vote in progress, I don't have time to do so right now.

**Comment by A1mDev** [comment]
This error is due to the fact that the event 'player_disconnect' is also called when changing the map, when the player leaves the game, when changing the map, the players partially reconnect to the server, so they cannot pass this [check](https://github.com/alliedmodders/sourcemod/blob/1fbe5e1daaee9ba44164078fe7f59d862786e612/core/logic/smn_players.cpp#L788-L790) (the same check as in sourcemod - IsClientInGame(client)).
