### ISSUE TITLE
The Passing Finale (c6m3_port) no items.

### ISSUE THREAD

**Issue by SirPlease** [SirPlease/L4D2-Competitive-Rework#48]
The second team gets **NOTHING** in the Saferoom (Guns/Ammo) and the "finale pills" won't spawn either.

**Things tried so far:**
- Prevent the removal of Items already added to the Stripper file.
- Filter out Spawns that could possibly overwrite our "enforced" method.
- Completely ignoring the existing Stripper file for the map.
- Actually filling up all the cans, completing the map for the first set of Survivors instead of slaying early.

This will be low priority, simply as "we" don't play this map in the vast majority of the competitive scene.

**Comment by Derpduck** [comment]
Is it just the weapons in the saferoom?
You could try setting `spawn_without_director` to `1` and `spawnflags` to `2` on the offending weapon spawns. The "fix" in the stripper files is only to make sure both types of tier 1 spawn, the "disappearing" comment is likely from when an HR spawning would cause the tier 1s to disappear, and since it replaces them with other tier 2 spawns that could be an issue too.
Not sure about the pills not spawning, if `spawnflags` set to `2` doesn't fix then it _could_ be related to how pills on finale are replaced.

**Comment by Derpduck** [comment]
Needs testing but this shouldn't happen in 2.0 / thesaccing_v2.vpk.
It could also be related to the old version of thesaccing.vpk as that addon completely removed c6m3 from the mission file, which allows the game to determine the gamemode the map is running on, which is probably what the issue is since the map supports all gamemodes and spawns items based on the gamemode.
