### ISSUE TITLE
Can not have addons as caster

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#512]
Even after reconnecting. Any reason? i have that in my cfg :

// [Addon Disabler]
// -----------------------------------------------------------------------   
// This Setting will disable/enable the Serverside Addon Disabler.
// -1 = use addonconfig.cfg
// 0 = Disable addons.
// 1 = Enable Addons
///////////////////////////////////////////////////////////////////////
sm_cvar l4d2_addons_eclipse 0

**Comment by lunatixxx** [comment]
I noticed that my rates don't get set to maximum as caster, it still considere me like a regular spectator apparently despite being in caster list in readyup menu.

**Comment by SirPlease** [comment]
I'm going to have a clean install 1:1 with the github later today on a new machine, so that'll allow me to test this. I'll get back to this in a few.

**Comment by lunatixxx** [comment]
Not using config loader if that matters, only have one.

**Comment by SirPlease** [comment]
It worked fine for me without issues, as expected.

Considering you're running a modified install, your rates may be caused because of [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/25fbd653dc71f61f4f070bb6ab1a28b4ac1ed4ee/addons/sourcemod/scripting/specrates.sp#L127) as it does require readyup to be available or it'll just skip the check.

As for the addons, make sure you have `caster_disable_addons` set to **0**.

**Comment by lunatixxx** [comment]
I did not know left4dhooks was creating an auto cfg, l4d2_addons_eclipse  was set on -1. It works now.

**Comment by SirPlease** [comment]
Did you solve your rates issue?
If so, please close the issue :)

**Comment by lunatixxx** [comment]
No i just removed specrates, server should be able to handle high rates anyway with only 16 slots.

**Comment by SirPlease** [comment]
It really comes down to the specs of the server and the tickrate (+nb_update_frequency)
