### ISSUE TITLE
tank and witchifier

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#519]
Tank and witch minimum avoidance cvar is not respected.
Witch banned percentage also.

**Comment by lunatixxx** [comment]
Boss vote broken after update.

**Comment by SirPlease** [comment]
I think the issue is caused by the builtinvotes we're compiling against.

**Comment by lunatixxx** [comment]
> I think the issue is caused by the builtinvotes we're compiling against.

It will need a new version of the extension?

**Comment by lunatixxx** [comment]
> Tank and witch minimum avoidance cvar is not respected. Witch banned percentage also.

Not consistent, sometimes it works and other times no.

**Comment by jensewe** [comment]
> Boss vote broken after update, can't vote at least if witch is enabled.

Try recompiling `l4d_boss_vote` because it seems like I didn't do that after I added an argument to `IsWitchPercentValid`. By the way, check out [builtinvotes updated by A1mDev](https://github.com/L4D-Community/builtinvotes/actions) if voting on your end is generally broken.

> > Tank and witch minimum avoidance cvar is not respected. Witch banned percentage also.
> 
> Not consistent, sometimes it works and other times no.

Do you use the PR one? From what I've tested before it works as intended. Would be helpful if you could also provide info generated from command `sm_tank_witch_debug_info` with ConVar `sm_tank_witch_debug` on.
P.S. A known issue that `!voteboss -1/any` will bug out on the passed in `-1`, will fix soon :)

**Comment by lunatixxx** [comment]
No i did go back to the previosu version and i could not vote because the witch percentage was banned, which did not work with this same version last time so it is weird.

Yes -1 glitch ui i already blocked it.

**Comment by jensewe** [comment]
[Updated Tankifier](https://github.com/jensewe/L4D2-Competitive-Rework/commit/64911f4871b6dec1a4f4a47b075835c093ad4260)
[Updated Boss Vote](https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/92dfc77d4cc3e5e0d2435660cc90217136ee26bd)

I've updated those, would be grateful if you can help confirm working :)
