### ISSUE TITLE
Need fix for dead center windows

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#535]
We were able to kill 2 survivors with jockeys only this is stupid, survivors do not grab the ledge.

**Comment by Derpduck** [comment]
Could you be more specific on which windows?
Survivors will not ledge hang if they don't resist the jockey either.

**Comment by Derpduck** [comment]
Can't reproduce, again could you be more specific or show an example?

**Comment by Derpduck** [comment]
If it isn't difficult to reproduce could you show 1 single example of it or 1 specific window where this happens?

**Comment by SirPlease** [comment]
I've gone ahead and attempted to reproduce it on my end, it seems like it's just the windows on the lower platform that are the problem.
All of them do show noticable ease with dropping out of the windows, while I couldn't get my character to run out of any of the top ones.

https://www.youtube.com/watch?v=pq2xFAOjPEw
In case you're early, I just uploaded the video so it might still be rendering.

**Comment by Derpduck** [comment]
It's not, it happens with or without them. I tested quite a lot, I'm pretty sure it's a universal bug its just easy to notice here but it could happen anywhere.

As far as I can tell it's caused by walking out of the window at a sharp enough angle that the game fails to find space for you to grab onto the ledge in time because of the walls on either side.
