### ISSUE TITLE
c2m1 tank bot navigation missing

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#625]
If someone lose the tank in the wrong place at the begining bot will go afk forever, players tend to ignore it or forget about it. He usually get stuck between the truck and the van so i tried to add props here with the hope that he will climb them but that does not help.

https://ibb.co/1fcc943

And the tank finally suicide after a while depsite having:
sm_cvar tank_stuck_time_suicide 999999999
sm_cvar tank_stuck_visibility_tolerance_suicide 999999999

**Comment by fantasylidong** [comment]
"If you don't modify the nav route of the game map, the AI robot won't climb the props you created."

**Comment by SirPlease** [comment]
Typically the only reason why adding props doesn't "entirely" break pathing for the Tank, Witch and Common infected is because they can each climb props when they're in their path.
While this can definitely be considered an issue, I personally don't see it as a very big deal.
The root cause is obviously just issues with map nav, which is something built into the map.

I've briefly looked at [this plugin](https://forums.alliedmods.net/showthread.php?p=2673222) in the past, but eventually figured you could achieve the same if not more with Stripper:Source.

**Comment by Derpduck** [comment]
The issue is that area doesn't have any nav mesh at all, so there's no way to connect it to tell the tank where to go, it will just walk in a straight line towards the survivors.
Aspects of the nav mesh can be edited with VScript but new navs can't be created since some stuff has to be pre-calculated.
