### ISSUE TITLE
Tickrate Enabler

### ISSUE THREAD

**Issue by dosergen** [SirPlease/L4D2-Competitive-Rework#67]
Hello , what about cvar tick_door_speed? Why doesn't work?

**Comment by SirPlease** [comment]
Hello, 

Afraid you'll have to be more specific, what do you mean with it not working?
The plugin is loaded by default, which is responsible for the cvar.

**Comment by dosergen** [comment]
05:26:22 plugin_print
05:26:22 Loaded plugins:
         ---------------------
         0:<TAB>"Metamod:Source 1.10.7-dev"
         1:<TAB>"Tickrate_Enabler 1.4-dev, ProdigySim"
         ---------------------
05:27:18 sm_cvar tick_door_speed
05:27:18 [SM] Unable to find cvar: tick_door_speed
05:28:37 sm_cvar nb_update_frequency
05:28:37 [SM] Value of cvar "nb_update_frequency": "0.033"
05:29:02 sm_cvar net_splitpacket_maxrate 
05:29:02 [SM] Value of cvar "net_splitpacket_maxrate": "128000"

**Comment by SirPlease** [comment]
You're looking at the Tickrate Enabler extension, the plugin that counters and attempts to minimize bugs caused by increasing the tickrate is listed under /addons/sourcemod/plugins/fixes and is called TickrateFixes.smx

It sounds like you've either only installed the repository partially or you've overwritten some files.
Having **sm_cvar match_execcfg_plugins "generalfixes.cfg;confogl_plugins.cfg;sharedplugins.cfg"** in your server.cfg is important as well.

**Comment by dosergen** [comment]
Sure , but the plugin you specified doesn't contain a fix for opening doors . TickrateFixes.smx contains fix guns and gravity. How can I return normal door opening at tickrate 100?

**Comment by SirPlease** [comment]
It does, I decompiled the plugin from github to make sure the version I had uploaded contains that fix.
The plugin contains all of them, I'm guessing you looked up an older version's source file?

**Comment by dosergen** [comment]
Yep, I use the old version of the plugin and it doesn't have this cvar. May I ask you to put the source code of the new version tickratefixes.smx? Thanks for help.
