### ISSUE TITLE
[Bug] Saferoom item remove

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#75]
I activated it only to kill end saferoom items, but sometimes it saves this state it seems and at the next map there is no weapons and medkits inside start saferoom. Installed l4d2util, saferoom detect and the saferoominfo files.

**Comment by lunatixxx** [comment]
Forgot to say i tested it in campaign mode, isn't it because this gamemode is saving the current state of the saferoom of the  previous map ? Hum i will try versus games later to be sure, but if it only happens in coop a fix will be good.

**Comment by lunatixxx** [comment]
Also less important, CSS weapons are not removed. (mp5 ect)

**Comment by SirPlease** [comment]
This is not a bug, the plugin is written for versus.
Map handling is different for coop, which is why it won't work as smoothly.
As for CSS weapons not being removed, the plugin is for competitive, more specifically the supported configs which is why it's not added to the remove Trie in **l4d2_saferoom_item**_remove plugin.

The code is available and you're welcome to modify it to your liking as long as you credit the original author.
