### ISSUE TITLE
[Question] Modules ?

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#80]
What do you need to use them ? I tried to compile one but it says 
plugin.sp(27) : warning 203: symbol is never used: "UL_OnClientPutInServer"
plugin.sp(10) : warning 203: symbol is never used: "UL_OnModuleStart"

And it does not work when installed.

**Comment by SirPlease** [comment]
Modules are included with the main plugin, in this case confoglcompmod.
They won't make sense if you compile them separately, and as you see, they won't work.
Looking into the modules isn't very useful as they're mostly disabled and replaced by standalone plugins, which is why a lot of people are wondering why we're not using **lgofnoc**.

If I didn't have a deadline to meet when I was rebuilding the framework, then I probably would've went with lgofnoc, but it's not a real biggie.

**Sidenote:** most of the issues you are creating are questions related to files in the github but they're not actual issues with the goal of the github and/or structure. I don't mind answering questions, but I'd prefer issues logged on here to be actual issues.
You're welcome to contact me on [Steam](https://steamcommunity.com/id/SirPlease/) personally for these matters.
